[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/sclevine/spec"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"
  version = "1.17.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
