required = ["github.com/maxbrunsfeld/counterfeiter"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/sclevine/spec"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"
  version = "1.17.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/dghubble/gologin"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "v2"
  name = "github.com/coreos/go-oidc"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfclient"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-incubator/uaa-cli"

[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"
