version: 2
jobs:
  build-go:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/pivotalservices/ignition
    steps:
      - checkout
      - run: |
          mkdir -p /tmp/output
          go get -u github.com/golang/dep/cmd/dep
          dep ensure
      - run: |
          go test ./... -covermode=atomic -coverprofile=coverage.txt
      - run: |
          GOOS=linux GOARCH=amd64 go build -o /tmp/output/ignition-linux-amd64 github.com/pivotalservices/ignition/cmd/ignition
      - persist_to_workspace:
          root: /tmp/output
          paths:
            - ignition-linux-amd64
  build-node:
    docker:
      - image: circleci/node:8
    working_directory: ~/ignition
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "web/package.json" }}
          - dependencies-

      - run:
          working_directory: web
          command: yarn install

      - save_cache:
          paths:
            - web/node_modules
          key: dependencies-{{ checksum "web/package.json" }}
      - run:
          working_directory: web
          command: yarn ci
      - persist_to_workspace:
          root: ~/ignition/web/dist
          paths:
            - index.html
            - assets/*
  package:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/ignition
    steps:
      - attach_workspace:
          at: ~/ignition
      - run:
          command: |
            cd ..
            tar -czf ignition.tar.gz ignition
      - store_artifacts:
          path: ~/ignition.tar.gz
          destination: ignition.tar.gz


workflows:
  version: 2

  package:
    jobs:
      - build-go
      - build-node
      - package:
          requires:
            - build-go
            - build-node
