---
applications:
- name: ignition
  memory: 128M
  instances: 2
  buildpack: binary_buildpack
  command: ./ignition
  services:
    - identity
  env:
    IGNITION_AUTH_VARIANT: "google"
    IGNITION_AUTH_URL: "https://accounts.google.com/o/oauth2/auth?approval_prompt=force&access_type=offline"
    IGNITION_TOKEN_URL: "https://accounts.google.com/o/oauth2/token"
    IGNITION_AUTH_SCOPES: "profile,email"
