---
applications:
- name: ignition
  memory: 128M
  instances: 2
  buildpack: binary_buildpack
  command: ./ignition
  services:
    - identity
  env:
    IGNITION_AUTH_VARIANT: "google"
    IGNITION_AUTH_DOMAIN: "https://accounts.google.com"
