---
applications:
- name: ignition-google
  memory: 128M
  instances: 2
  buildpack: binary_buildpack
  command: ./ignition
  services:
    - ignition-google-config
  env:
    IGNITION_CONFIG_SERVICENAME: "ignition-google-config"
