groups: []

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: ignition
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotalservices/ignition.git

- name: pr
  type: pull-request
  source:
    username: goulash-ci
    uri: git@github.com:pivotalservices/ignition.git
    repo: pivotalservices/ignition
    access_token: {{github-access-token}}
    private_key: {{git-private-key}}

- name: version
  type: semver
  source:
    initial_version: 0.0.1-rc.1
    driver: git
    uri: git@github.com:pivotalservices/ignition.git
    branch: version
    file: version
    private_key: {{git-private-key}}

jobs:
- name: test-and-build
  plan:
  - get: ignition
    resource: pr
    trigger: true
  - aggregate:
    - do:
      - task: install-node-dependencies
        file: ignition/ci/install-node-dependencies.yml
      - aggregate:
        - task: build-assets
          file: ignition/ci/build-node.yml
        on_failure:
          aggregate:
            - put: pr
              params:
                path: ignition
                status: failure
    - do:
      - task: install-go-dependencies
        file: ignition/ci/install-go-dependencies.yml
      - aggregate:
        - task: unit
          file: ignition/ci/unit.yml
        - task: build
          file: ignition/ci/build-go.yml
        on_failure:
          aggregate:
            - put: pr
              params:
                path: ignition
                status: failure
  - put: pr
    params:
      path: ignition
      status: success

- name: create-rc
  serial_groups: [version]
  plan:
  - aggregate:
    - get: ignition
      trigger: true
    - get: version
      params: {pre: rc}
  - aggregate:
    - do:
      - task: install-node-dependencies
        file: ignition/ci/install-node-dependencies.yml
      - aggregate:
        - task: build-assets
          file: ignition/ci/build-node.yml
    - do:
      - task: install-go-dependencies
        file: ignition/ci/install-go-dependencies.yml
      - aggregate:
        - task: unit
          file: ignition/ci/unit.yml
        - task: build
          file: ignition/ci/build-go.yml
